# deli后台登录账号密码
deli:
  mobile: 
  password: 

# 导出日期范围
# 日期可以正常格式如"2019-1-1"
# 也可为特定词汇today表示今天
# 当from为today时，表明从今天起，未来每天都只当初当天结果
# 当from为基础格式时，表明只导出某个时间段内的记录
date:
  from: 2019-11-26
  to: 2019-11-26

crawl:
  spec: 0 0 */1 * * *
  concurrency_num: 1
  # 抓取提留时间，避免被封 IP，支持 Duration 格式，比如 10s
  sleep: 10s

log:
  dir: '/log/'

storage:
  driver: mysql
  user: root
  password: 
  host: 192.168.1.10
  port: 3306
  dbname: deli
  charset: utf8mb4

excel:
    dir: E:/GitHub/deli-crawler/excel/

cookie:
  gr_user_id: 
  sensorsdata: 
  grwng_uid: 
  gr_session_id_8: 
  c_gr_session_id: 
  c_gr_session_id_53: 
  gr_session_id_9: 
  gr_session_id_95: 
